// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8rB3Ej6AYXW6HSsRmchErkYNB50iqSZM',
    appId: '1:445103469654:web:345b80ae86a972f64237f7',
    messagingSenderId: '445103469654',
    projectId: 'flutter-4e3e6',
    authDomain: 'flutter-4e3e6.firebaseapp.com',
    databaseURL: 'https://flutter-4e3e6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4e3e6.appspot.com',
    measurementId: 'G-6FR5ZTHF10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuR-YKHzX6QeV4wJPG6iZprBGZ4DQjWAQ',
    appId: '1:445103469654:android:21d07c29fd091d544237f7',
    messagingSenderId: '445103469654',
    projectId: 'flutter-4e3e6',
    databaseURL: 'https://flutter-4e3e6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4e3e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZQbNj90Pp9_BMuHwPtvrz_D8zNK6ly94',
    appId: '1:445103469654:ios:b1723347521129334237f7',
    messagingSenderId: '445103469654',
    projectId: 'flutter-4e3e6',
    databaseURL: 'https://flutter-4e3e6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4e3e6.appspot.com',
    iosClientId: '445103469654-ur13fhivphfl4du185to768prhal4uc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZQbNj90Pp9_BMuHwPtvrz_D8zNK6ly94',
    appId: '1:445103469654:ios:15356d790d208e6f4237f7',
    messagingSenderId: '445103469654',
    projectId: 'flutter-4e3e6',
    databaseURL: 'https://flutter-4e3e6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4e3e6.appspot.com',
    iosClientId: '445103469654-i3kb2rjb203qubusc5tfoo2h3pipj5na.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
